version: '3.9'

services:
  client:
    container_name: ucrm-client
    build: ./
    environment:
      - PORT=3000
    networks:
      ucrm-client:
        ipv4_address: ${NETWORK_PREFIX:-173.4}.4.12
        aliases:
          - ucrm.client.loc

  nginx:
    container_name: ucrm-nginx
    depends_on:
      - client
    build: ./nginx
    ports:
      - 8080:80
    networks:
      ucrm-client:
        ipv4_address: ${NETWORK_PREFIX:-173.4}.4.14
        aliases:
          - ucrm.nginx.loc

networks:
  ucrm-client:
    name: ucrm-client
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX:-173.4}.4.0/24
