version: '3.9'

services:
  client:
    container_name: ucrm-client
    build: ./
    networks:
      - private
      # ucrm:
      #   ipv4_address: 172.4.4.12
      #   aliases:
      #     - ucrm.client.loc

  nginx:
    container_name: ucrm-nginx
    depends_on:
      - client
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - private
      # ucrm:
      #   ipv4_address: 172.4.4.14
      #   aliases:
      #     - ucrm.client.loc:3000

networks:
  private:
#   ucrm:
#     name: ucrm
#     ipam:
#       config:
#         - subnet: 172.4.4.0/24
