name: Build and Lint

on:
  pull_request:

jobs:
  web-client-build:
    name: Nextjs Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 'Build'
        run: |
          yarn
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn lint
          yarn build
