name: Build and Lint

on:
  pull_request:

jobs:
  go-build:
    name: Go app build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: cd ./services && CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o ucrm.app ./cmd/app/main.go

  front-build:
    name: Vue build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
        
      - name: 'Build'
        run: |
          cd ./frontend
          yarn
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn lint
          yarn build
