name: Docker Push

on:
  workflow_dispatch:
    branches:
      - master
      - release
    inputs:
      version:
        description: "Version"
        required: true
  push:
    branches: [release]

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          export event_tag=${{ github.event.inputs.version }}
          if [! -z $event_tag]; then
            export IMAGE_TAG=${{ github.event.inputs.version }}
          else
            export IMAGE_TAG=${{ github.sha }}
          fi
          docker build --build-arg version="$IMAGE_TAG" --no-cache -f ./Dockerfile -t ucrm-web .
          docker tag ucrm-web "ghcr.io/${{ github.repository }}:$IMAGE_TAG"
          docker tag ucrm-web "ghcr.io/${{ github.repository }}:latest"
      - name: Push Image
        run: |
          export event_tag=${{ github.event.inputs.version }}
          if [! -z $event_tag]; then
            export IMAGE_TAG=${{ github.event.inputs.version }}
          else
            export IMAGE_TAG=${{ github.sha }}
          fi
          docker push "ghcr.io/${{ github.repository }}:$IMAGE_TAG"
          docker push "ghcr.io/${{ github.repository }}:latest"
